### ISSUE TITLE
Keyboard navigation for Jailbreak, SBAHJ, & Ryanquest

### ISSUE THREAD

**Issue by Stevoisiak** [recordcrash/homestuck-companion#5]
Currently, page navigation with the keyboard is supported for [_Homestuck_](https://www.homestuck.com/story) and [_Problem Sleuth_](https://www.homestuck.com/problem-sleuth). It would be convenient to have keyboard navigation added for the other MSPA comics [_Jailbreak_](https://www.homestuck.com/jailbreak), [_Sweet Bro and Hella Jeff_](https://www.homestuck.com/sweet-bro-and-hella-jeff), and [_Ryanquest_](https://www.homestuck.com/ryanquest).

(Excluding [_Bard Quest_](https://www.homestuck.com/bard-quest) due to its "choose your own adventure" format)

**Comment by recordcrash** [comment]
It's done! Forgot to close this.

**Comment by Stevoisiak** [comment]
> It's done! Forgot to close this.

Thanks! As a tip, if you include `closes #5` or `fixes #5` in the commit message, merging will [auto-close the linked issue](https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords#about-issue-references).

(The commit message `This closes issue #5` doesn't count.)
